# Generated by Django 2.2.9 on 2020-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200716_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_logo',
            new_name='company_logo1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='company_name',
            new_name='company_name1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='company_name2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_image1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_image2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_title1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_title2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='skiills_One',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_Four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_Three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_Two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='title2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
