# Generated by Django 2.2.9 on 2020-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200716_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('skills_Description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Skills_overview',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='development_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='development_type1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='development_type2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_image1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_image2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_title1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_title2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skiills_One',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skiills_three',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skiills_two',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills_One',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills_Two',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills_three',
        ),
    ]
