# Generated by Django 2.2.9 on 2020-07-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200716_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Second_Backend',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_Backend',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='title1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
