# Generated by Django 2.2.9 on 2020-07-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200716_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_Desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_img',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
