# Generated by Django 2.2.9 on 2020-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200716_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_img_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_img_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
