# Generated by Django 2.2.9 on 2020-07-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200716_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
