# Generated by Django 2.2.9 on 2020-07-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_profile_company_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_title1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_title2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
