# Generated by Django 2.2.9 on 2020-07-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200717_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Second_Backend',
            new_name='icon_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_title1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_title2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_Backend',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_img_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_img_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tool_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tool_title',
        ),
    ]
