# Generated by Django 2.2.9 on 2020-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200717_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_Desc', models.TextField(blank=True)),
                ('portfolio_img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('first_language', models.CharField(blank=True, max_length=200)),
                ('secon_language', models.CharField(blank=True, max_length=200)),
                ('icon_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='icon_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_Desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secon_language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
