# Generated by Django 2.2.9 on 2020-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_portfolio_portfolio_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills_description',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skills_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
