# Generated by Django 2.2.9 on 2020-07-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_portfolio_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
